# To use this script, you must have the following variables defined
# You can define them at the project or the group level
#
# SONAR_URL:   Full URL to the SonarQube server
# SONAR_TOKEN: API token for SonarQube


stages:
  - QA
  
SonarQube:
  stage: QA
  image: its-registry.unl.edu/unl-its/docker-ci/static-code-analysis:php
  tags:
    - docker
  only:
    - master
  cache:
    policy: pull
    paths:
      - dep_check
  script:
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
      -Dsonar.projectKey=$CI_PROJECT_PATH_SLUG -Dsonar.projectName="$CI_PROJECT_TITLE"
      -Dsonar.sources=.
      -Dsonar.dependencyCheck.reportPath=./dep_check/dependency-check-report.xml
      -Dsonar.dependencyCheck.jsonReportPath=./dep_check/dependency-check-report.json
      -Dsonar.dependencyCheck.htmlReportPath=./dep_check/dependency-check-report.html
