controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# app_index_page:
#     path: /
#     controller: App\Controller\IndexController::homepage
